### ISSUE TITLE
"step 4: Customizing and building a buildroot project" make fail

### ISSUE THREAD

**Issue by chenguoping76** [farbius/linux-vitis-zynq#1]
using buildroot 2023.02.6 to test zynq_arty example project:

![V(W63)K%2}$1ER~TB5B8JJR](https://github.com/farbius/linux-vitis-zynq/assets/35511222/c8f97571-0344-4d0f-b1ed-2bf9d021ceca)

![)KSG 9~V$Q 2JA~P2R( W(I](https://github.com/farbius/linux-vitis-zynq/assets/35511222/50ab5dcf-f048-444d-8d78-8636d34dc3ac)

**Comment by farbius** [comment]
the issue is caused by the configuration file (_defconfig) and new version of Buildroot. In the defconfig there are some configuration  that are not suppordet in newest version of Buildroot.

**Comment by chenguoping76** [comment]
So, which version of buildroot recommendation ? Or improved zynq_defconfig should by give ? THX


Guoping 



28th, Oct., 2023
 
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Aleksei&nbsp;Rostov"; 
Date: 2023年10月28日(星期六) 下午3:50
To: "farbius/linux-vitis-zynq"; 
Cc: "陈国平"; "Author"; 
Subject: Re: [farbius/linux-vitis-zynq] &quot;step 4: Customizing and building a buildroot project&quot; make fail (Issue #1)

&nbsp;


 
the issue is caused by the configuration file (_defconfig) and new version of Buildroot. In the defconfig there are some configuration  that are not suppordet in newest version of Buildroot

**Comment by chenguoping76** [comment]
I change a buildroot (port by mathworks R2022.1) the legacy gone, but&nbsp;





so, I think correct buildroot (which check-kernel-headers.sh suit for your zynq_defconfig's&nbsp; linux kernel ) maybe work well ?&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, Oct 28, 2023 03:50 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [farbius/linux-vitis-zynq] "step 4: Customizing and building a buildroot project" make fail (Issue #1)

&nbsp;



 
the issue is caused by the configuration file (_defconfig) and new version of Buildroot. In the defconfig there are some configuration  that are not suppordet in newest version of Buildroot

**Comment by wangzhiwei18** [comment]
Have you solve the problem?
I met the same problem.
Could you please tell me which version of buildroot to choose?

**Comment by chenguoping76** [comment]
buildroot 2017.04 maybe work

**Comment by farbius** [comment]
in buildroot folder there is Config.in.legacy, here is list of packages, that are not supported any more. These packages should be deleted from _defconfig. I updated defconfigs and  added build_zynq.sh, build_zynqmp.sh to compile buildroot project for 2023.5 version

**Comment by chenguoping76** [comment]
@farbius great works! and more would your can give us some hints that why the spl/boot.bin generated by uboot can not using to load the uboot.img? actually spl/boot.bin act as the fsbl generated by vitis.
thx!

**Comment by chenguoping76** [comment]
@farbius great works! and more would your can give us some hints that why the spl/boot.bin generated by uboot can not using to load the uboot.img? actually spl/boot.bin act as the fsbl generated by vitis.
thx!

**Comment by farbius** [comment]
I don’t use secondary program loader, since it cannot be used with Zynqmp devices.
